AWSTemplateFormatVersion: '2010-09-09'
Description: Turns on CloudTrail and saves logs locally and sends logs to the centralized logging account.

Parameters:
  CentralizedCloudTrailBucketName:
    Description: Centralized CloudTrail S3 bucket that will recieve logs from this account and from others (must already exist).
    Type: String
    Default: "organization-cloudtrail-logs"
  CentralizedKMSKeyArn:
    Description: The KMS key ARN in the centralized logging account to be used to encrypt CloudTrail Logs (must already exist).
    Type: String
    Default: arn:aws:kms:us-west-2:111111111111:key/some-key-guid
  CentralizedCloudTrailName:
    Description: 'Name given to the Centralized CloudTrail logs configuration'
    Type: String
    Default: "organization-cloudtrail-logging-acct"
  CentralizedEncryptLogs:
    Description: Indicates whether the logs stored in the Centralized S3 bucket should be encrypted or not.
    Type: String
    Default: "true"
    AllowedValues: 
      - "true"
      - "false"

  ConfigureLocalCloudTrail:
    Description: Enable CloudTrail in this (local) account
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  LocalEncryptLogs:
    Description: Indicates whether the logs stored in the Local S3 bucket should be encrypted or not.
    Type: String
    Default: "true"
    AllowedValues: 
      - "true"
      - "false"
  LocalCloudTrailBucketName:
    Description: The Local S3 bucket that will be storing CloudTrail logs from this account.
    Type: String
    Default: "organization-acct-cloudtrail"
  LocalCloudTrailName:
    Description: 'Name given to the Local CloudTrail logs configuration'
    Type: String
    Default: "organization-acct-cloudtrail"
  LocalKMSKeyName:
    Description: 'Alias given to the KMS key used to encrypt CloudTrail Logs (ignored if Encrypt Logs is set to false)'
    Type: String
    Default: "cloudtrail-key"


  MultiRegion:
    Description: Indicates whether the CloudTrail trail is created in the region in which you create the stack (false) or in all regions (true).
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  IncludeGlobalEvents:
    Description: Indicates whether the trail is publishing events from global services, such as IAM, to the log files.
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  EnableLogFileValidation:
    Description: Indicates whether CloudTrail validates the integrity of log files.
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  ReadWriteType:
    Description: Specifies whether to log read-only events, write-only events, or all events.
    Type: String
    Default: All
    AllowedValues:
      - ReadOnly
      - WriteOnly
      - All

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Centralized KMS & Bucket Config
        Parameters:
          - CentralizedCloudTrailBucketName
          - CentralizedCloudTrailName
          - CentralizedEncryptLogs
          - CentralizedKMSKeyArn
      - Label:
          default: Local Acct KMS & Bucket Config
        Parameters:
          - ConfigureLocalCloudTrail
          - LocalCloudTrailBucketName
          - LocalCloudTrailName
          - LocalEncryptLogs
          - LocalKMSKeyName
      - Label:
          default: General CloudTrail Options (for both Centralized and Local)
        Parameters:
          - MultiRegion
          - IncludeGlobalEvents
          - EnableLogFileValidation
          - ReadWriteType
    ParameterLabels:
      CentralizedCloudTrailBucketName:
        default: Centralized CloudTrail Bucket Name
      CentralizedCloudTrailName:
        default: Centralized CloudTrail Name
      CentralizedKMSKeyArn:
        default: Centralized Logging Acct KMS Key ARN
      CentralizedEncryptLogs:
        default: Encrypt Logs in Centralized Logging Acct
      LocalCloudTrailBucketName:
        default: CloudTrail Bucket Name
      LocalKMSKeyName:
        default: KMS Key Name
      ConfigureLocalCloudTrail:
        default: Configure CloudTrail Locally
      LocalEncryptLogs:
        default: Encrypt Logs
      LocalCloudTrailName:
        default: CloudTrail Log Name
      MultiRegion:
        default: Multi Region
      IncludeGlobalEvents:
        default: Include Global Events
      EnableLogFileValidation:
        default: Enable Log File Validation
      ReadWriteType:
        default: Event Types To Log

Conditions:
    LocalCloudTrail:
      !Equals ['true', !Ref 'ConfigureLocalCloudTrail']
    ShouldEncryptCentralizedLogs:
      !Equals ['true', !Ref 'CentralizedEncryptLogs']
    ShouldEncryptLocalLogs:
      !Equals ['true', !Ref 'LocalEncryptLogs']


Resources:
  # Centralized CloudTrail
  CentralizedCloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      EnableLogFileValidation: !Ref EnableLogFileValidation
      IncludeGlobalServiceEvents: !Ref IncludeGlobalEvents
      IsLogging: true
      IsMultiRegionTrail: !Ref MultiRegion
      EventSelectors: 
        - ReadWriteType: !Ref ReadWriteType
      S3BucketName: !Ref 'CentralizedCloudTrailBucketName'
      KMSKeyId: !If [ ShouldEncryptCentralizedLogs, !Ref 'CentralizedKMSKeyArn', !Ref "AWS::NoValue" ] 
      TrailName: !Ref CentralizedCloudTrailName


  # Local CloudTrail
  LocalAccountCloudTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: LocalCloudTrailBucket
    Condition: LocalCloudTrail
    Properties:
      EnableLogFileValidation: !Ref EnableLogFileValidation
      IncludeGlobalServiceEvents: !Ref IncludeGlobalEvents
      IsLogging: true
      IsMultiRegionTrail: !Ref MultiRegion
      EventSelectors: 
        - ReadWriteType: !Ref ReadWriteType
      S3BucketName: !Ref LocalCloudTrailBucketName
      KMSKeyId: !If [ ShouldEncryptLocalLogs, !GetAtt LocalCloudTrailEncryptionKey.Arn, !Ref "AWS::NoValue" ] 
      TrailName: !Ref LocalCloudTrailName
  
  LocalCloudTrailBucket:
    Type: AWS::S3::Bucket
    Condition: LocalCloudTrail
    Properties:
      BucketName: !Ref LocalCloudTrailBucketName
  
  CloudTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: LocalCloudTrail
    Properties:
      Bucket: !Ref LocalCloudTrailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub "arn:aws:s3:::${LocalCloudTrailBucketName}"
          - Sid: CloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource:
              - !Sub "arn:aws:s3:::${LocalCloudTrailBucketName}/AWSLogs/${AWS::AccountId}/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
  
  LocalCloudTrailEncryptionKey:
    Type: AWS::KMS::Key
    Condition: ShouldEncryptLocalLogs
    Properties:
      Description: Used for CloudTrail logs encryption.
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Id: Key policy created by CloudTrail
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: kms:*
            Resource: '*'
          - Sid: Allow CloudTrail to encrypt logs
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: kms:GenerateDataKey*
            Resource: '*'
            Condition:
              StringLike:
                kms:EncryptionContext:aws:cloudtrail:arn:
                  - !Sub "arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*"
          - Sid: Allow CloudTrail access
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: kms:DescribeKey
            Resource: '*'
          - Sid: Enable CloudTrail log decrypt permissions
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - kms:Decrypt
              - kms:ReEncryptFrom
            Resource: '*'
            Condition:
              StringEquals:
                kms:CallerAccount: !Ref 'AWS::AccountId'
              StringLike:
                kms:EncryptionContext:aws:cloudtrail:arn: !Sub "arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*"
          - Sid: Allow alias creation during setup
            Effect: Allow
            Principal:
              AWS: '*'
            Action: kms:CreateAlias
            Resource: '*'
            Condition:
              StringEquals:
                kms:ViaService: !Sub ec2.${AWS::Region}.amazonaws.com
                kms:CallerAccount: !Ref 'AWS::AccountId'
  
  
  LocalCloudTrailEncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Condition: ShouldEncryptLocalLogs
    Properties:
      AliasName: !Sub 'alias/${LocalKMSKeyName}'
      TargetKeyId: !Ref 'LocalCloudTrailEncryptionKey'